### ISSUE TITLE
When do you plan to release the code？

### ISSUE THREAD

**Issue by ykj467422034** [mtablo/ALE_Edit_page#1]

**Comment by mtablo** [comment]
Thank you for your interest in our work.
We are currently in the review process, and plan to release the source code and benchmark upon acceptance.

We will notify you when we release the source code.

**Comment by mtablo** [comment]
Thank you for your patience!
The official implementation of ALE (Attribute-Leakage-free Editing) has now been released.
You can find the code and benchmark here: https://github.com/ml-postech/ALE
